import Foundation

public struct CaptureCandidate: Sendable {
    public var sourceBundleID: String?
    public var types: Set<String>
    public var plainText: String?

    public init(sourceBundleID: String?, types: Set<String>, plainText: String?) {
        self.sourceBundleID = sourceBundleID
        self.types = types
        self.plainText = plainText
    }
}

public struct PrivacyConfiguration: Sendable, Equatable {
    public var ignoreConfidential: Bool
    public var ignoreTransient: Bool
    public var ignoredBundleIDs: Set<String>

    public init(
        ignoreConfidential: Bool = true,
        ignoreTransient: Bool = true,
        ignoredBundleIDs: Set<String> = [
            "com.apple.Passwords",
            "com.apple.keychainaccess",
            "com.agilebits.onepassword7",
            "com.1password.1password"
        ]
    ) {
        self.ignoreConfidential = ignoreConfidential
        self.ignoreTransient = ignoreTransient
        self.ignoredBundleIDs = ignoredBundleIDs
    }
}

public enum CaptureIgnoredReason: String, Sendable, Equatable {
    case internalWrite
    case ignoredApplication
    case concealed
    case transient
    case confidential
}

public enum CaptureDecision: Sendable, Equatable {
    case allowed
    case ignored(CaptureIgnoredReason)
}

public struct PrivacyPolicy: Sendable {
    public static let internalMarkerType = "dev.clipcanvas.internal-write"

    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "com.agilebits.onepassword",
        "com.apple.passwordmanager"
    ]
    private static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    public let configuration: PrivacyConfiguration

    public init(configuration: PrivacyConfiguration) {
        self.configuration = configuration
    }

    public func evaluate(_ candidate: CaptureCandidate) -> CaptureDecision {
        if candidate.types.contains(Self.internalMarkerType) {
            return .ignored(.internalWrite)
        }
        if let sourceBundleID = candidate.sourceBundleID,
           configuration.ignoredBundleIDs.contains(sourceBundleID) {
            return .ignored(.ignoredApplication)
        }
        if configuration.ignoreTransient {
            if !candidate.types.isDisjoint(with: Self.concealedTypes) {
                return .ignored(.concealed)
            }
            if !candidate.types.isDisjoint(with: Self.transientTypes) {
                return .ignored(.transient)
            }
        }
        if configuration.ignoreConfidential,
           let text = candidate.plainText,
           Self.looksConfidential(text) {
            return .ignored(.confidential)
        }
        return .allowed
    }

    private static func looksConfidential(_ text: String) -> Bool {
        guard !text.isEmpty, text.count <= 100_000 else { return false }
        let patterns = [
            #"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"#,
            #"(?i)\b(?:api[_-]?key|access[_-]?token|client[_-]?secret|password)\b\s*[:=]\s*["']?[A-Za-z0-9_./+\-]{20,}"#,
            #"\bAKIA[0-9A-Z]{16}\b"#,
            #"\bsk_(?:live|test)_[A-Za-z0-9]{20,}\b"#,
            #"\bgh[opsu]_[A-Za-z0-9]{30,}\b"#
        ]
        let range = NSRange(text.startIndex..<text.endIndex, in: text)
        return patterns.contains { pattern in
            guard let expression = try? NSRegularExpression(pattern: pattern) else {
                return false
            }
            return expression.firstMatch(in: text, range: range) != nil
        }
    }
}
